export const dummyData = [
  {
    id: 1,
    sehir: "GAZİANTEP",
    personel: ["Sümeyra Al", "Canan Tütünen"],
    merkez1: "<b>Nurdağı 1 Konteyner Kenti</b>- Görüşme konteynerı",
    merkez2:
      "<b>Mobil Ekip</b> (Nurdağı B-1 C1, TOKİ Konteyner Eğitim Kampüsü, Ahbap Okulları, Nurdağı 2, Fatih Mah. Yeni Mah. Kurudere Mah. )",
    tel1: "0532 330 16 33",
    tel2: "0539 774 35 75",
    kurum1: "WHR",
    kurum2: "AÇEV",
    kurum3: "ASHB",
    kurum4: "Sağlık Bakanlığı",
    kurum5: "GASMEK",
    kurum6: "Halk Eğitim Merkezi",
    kurum7: "TOG",
    kurum8: "Gaziantep Yardım Vakfı",
    kurum9: "Empati Derneği",
    kurum10: "KAÇUV",
    kurum11: "Diyanet",
    kurum12:
      "Yöret-Roman Diyalog Ağı - Sıfır Ayrımcılık Derneği (işbirliği için iletişime geçildi)",
    kisi: "1 Nisan-1 Mayıs aralığında ulaşılan kişi sayısı 1000",
  },
  {
    id: 2,
    sehir: "KİLİS",
    personel: ["Sümeyra Al", "Canan Tütünen"],
    merkez1: "<b>Nurdağı 1 Konteyner Kenti</b>- Görüşme konteynerı",
    merkez2:
      "<b>Mobil Ekip</b> (Nurdağı B-1 C1, TOKİ Konteyner Eğitim Kampüsü, Ahbap Okulları, Nurdağı 2, Fatih Mah. Yeni Mah. Kurudere Mah. )",
    tel1: "0532 330 16 33",
    tel2: "0539 774 35 75",
    kurum1: "WHR",
    kurum2: "AÇEV",
    kurum3: "ASHB",
    kurum4: "Sağlık Bakanlığı",
    kurum5: "GASMEK",
    kurum6: "Halk Eğitim Merkezi",
    kurum7: "TOG",
    kurum8: "Gaziantep Yardım Vakfı",
    kurum9: "Empati Derneği",
    kurum10: "KAÇUV",
    kurum11: "Diyanet",
    kurum12:
      "Yöret-Roman Diyalog Ağı - Sıfır Ayrımcılık Derneği (işbirliği için iletişime geçildi)",
    kisi: "1 Nisan-1 Mayıs aralığında ulaşılan kişi sayısı 1000",
  },
  {
    id: 3,
    sehir: "BURSA",
    personel: ["Sümeyra Al", "Canan Tütünen"],
    merkez1: "<b>Nurdağı 1 Konteyner Kenti</b>- Görüşme konteynerı",
    merkez2:
      "<b>Mobil Ekip</b> (Nurdağı B-1 C1, TOKİ Konteyner Eğitim Kampüsü, Ahbap Okulları, Nurdağı 2, Fatih Mah. Yeni Mah. Kurudere Mah. )",
    tel1: "0532 330 16 33",
    tel2: "0539 774 35 75",
    kurum1: "WHR",
    kurum2: "AÇEV",
    kurum3: "ASHB",
    kurum4: "Sağlık Bakanlığı",
    kurum5: "GASMEK",
    kurum6: "Halk Eğitim Merkezi",
    kurum7: "TOG",
    kurum8: "Gaziantep Yardım Vakfı",
    kurum9: "Empati Derneği",
    kurum10: "KAÇUV",
    kurum11: "Diyanet",
    kurum12:
      "Yöret-Roman Diyalog Ağı - Sıfır Ayrımcılık Derneği (işbirliği için iletişime geçildi)",
    kisi: "1 Nisan-1 Mayıs aralığında ulaşılan kişi sayısı 1000",
  },
];
